/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIModelConfig: typeof import('./components/AIModelConfig.vue')['default']
    AIModelConfigDialog: typeof import('./components/AIModelConfigDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ConversationHistory: typeof import('./components/ConversationHistory.vue')['default']
    DataCard: typeof import('./components/DataCard.vue')['default']
    DatasetChips: typeof import('./components/DatasetChips.vue')['default']
    DatasetList: typeof import('./components/DatasetList.vue')['default']
    DatasetManagement: typeof import('./components/DatasetManagement.vue')['default']
    DatasetPreviewDialog: typeof import('./components/DatasetPreviewDialog.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DocumentPreview: typeof import('./components/DocumentPreview.vue')['default']
    EChart: typeof import('./components/EChart.vue')['default']
    FileUploadDialog: typeof import('./components/FileUploadDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    MarkdownRenderer: typeof import('./components/MarkdownRenderer.vue')['default']
    MinIOManager: typeof import('./components/MinIOManager.vue')['default']
    MockChart: typeof import('./components/MockChart.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    OriginalFilePreviewDialog: typeof import('./components/OriginalFilePreviewDialog.vue')['default']
    ProcessingSteps: typeof import('./components/ProcessingSteps.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/StatCard.vue')['default']
    ToolMenu: typeof import('./components/ToolMenu.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
    VueOfficePreview: typeof import('./components/VueOfficePreview.vue')['default']
    WebScraperManager: typeof import('./components/WebScraperManager.vue')['default']
  }
}
